Add veranstaltungstickets info
matrix-org/matrix-conf-website pull request #37
Opened 2024-06-17 14:38 UTC by thibaultamartin

2024-06-17 14:38 UTC, thibaultamartin commented
@HarHarLinks eyes welcome here too

2024-06-17 14:54 UTC, HarHarLinks requested changes
i would move the paragraph to before the local bus part. first train, then bus.

2024-06-17 14:54 UTC, HarHarLinks commented on templates/attend.html
> +                            "veranstaltungstickets"</a>. Those are only valid with a Matrix Conference ticket!</p>
```suggestion
                    <p>The Matrix Conference is eligible for the <a
                            href="https://www.veranstaltungsticket-bahn.de/?event=20421&language=en">buying
                            "Veranstaltungsticket"</a> special offer by Deutsche Bahn for holders of 
                            Matrix Conference tickets!</p>
```

2024-06-18 09:18 UTC, HarHarLinks commented on templates/attend.html
> +                            href="https://www.veranstaltungsticket-bahn.de/?event=20421&language=en">buying
```suggestion
                            href="https://www.veranstaltungsticket-bahn.de/?event=20421&language=en">
```

2024-06-18 09:19 UTC, HarHarLinks commented on templates/attend.html
> +                            "Veranstaltungsticket"</a> special offer by Deutsche Bahn for holders of
```suggestion
                    <p>The Matrix Conference is eligible for the "<a
                            href="https://www.veranstaltungsticket-bahn.de/?event=20421&language=en">
                            Veranstaltungsticket</a>" special offer by Deutsche Bahn for holders of 
```

2024-06-18 09:44 UTC, HarHarLinks commented
ehhh can you remove the extra space between `"` and Veranstaltungsticket? also I think we use different quotes across the website. some are fancier than others maybe originating from gdocs (did I say to get rid of google yet today?)

2024-06-18 12:16 UTC, merged